version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/UsageMeter.App
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /src/UsageMeter.Core
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /tests/UsageMeter.Tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
